title: 
author:
  name: GitHub User
  email: rgupta460@gtech.edu
logo: /assets/photo.png
#description: text below image
description: >
  I am an active researcher in the field of optimized operation and planning
  of power system interfaced with a large amount of renewable energy resources.
  My current focus is on developing realistic synthetic network models of power system for hosting capacity analysis.
#show_downloads: true
theme: jekyll-theme-minimal
